# base image
FROM python:3.7.0-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd && \
    apk add libffi-dev

# set working directory
WORKDIR /usr/src/app

# add app
COPY . /usr/src/app
RUN pip install -r requirements.txt
